apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    app: applets-ecol-device-security
  name: applets-ecol-device-security
spec:
  ports:
  - name: "applets-ecol-device-security"
    port: 8080
    targetPort: 8080
  selector:
    app: applets-ecol-device-security
status:
  loadBalancer: {}
