apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    app: data-report
  name: data-report
spec:
  selector:
    matchLabels:
      app: data-report
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: data-report
    spec:
      containers:
      - env:
        - name: ACCOUNT_PROVIDER_URL
          value: http://applets-ecol-account:8080/api/v1/mop/applets-ecol-account/organ/platform/account/organInfo/
        - name: KAFKA_ADDESS
          value: kafka:9092
        - name: MONGO_URL
          value: mongo
        - name: PUB_ENV
          value: mop-community
        image: {{ .Values.images.data_report }}
        name: data-report
        resources: {}
      restartPolicy: Always
      
        
status: {}
