apiVersion: batch/v1
kind: Job
metadata:
  labels:
    io.kompose.service: gateway-init
  name: gateway-init
spec:
  template:
    metadata:
      name: gateway-init
      labels:
        io.kompose.service: gateway-init
    spec:
      imagePullSecrets:
        - name: {{ .Values.k8s_imagePullSecrets }}
      containers:
      - env:
        - name: API_GATEWAY_ENV
          value: mop-compose
        - name: KONG_ADMIN_URL
          value: http://gateway:8001
        - name: LOG_LEVEL
          value: info
        image: {{ .Values.images.gateway_init }}
        imagePullPolicy: Always
        name: gateway-init
      restartPolicy: OnFailure
