apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: kong-db
  name: kong-db
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: kong-db
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: kong
        - name: POSTGRES_MULTIPLE_DATABASES
          value: "konga,mop-private-applets-ecol-account"
        - name: POSTGRES_PASSWORD
          value: kong@@123321
        - name: POSTGRES_USER
          value: kong
        - name: TZ
          value: Asia/Shanghai
        image: {{ .Values.images.kong_db }}
        name: kong-db
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: kong-db-claim0
          subPath: data
      restartPolicy: Always
      imagePullSecrets:
        - name: {{ .Values.k8s_imagePullSecrets }}
      volumes:
      - name: kong-db-claim0
        persistentVolumeClaim:
          claimName: kong-db-claim0
status: {}
