apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    app: minio
  name: minio
spec:
  selector:
    matchLabels:
      app: minio
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: minio
    spec:
      containers:
      - args:
        - server
        - /data
        env:
        - name: MINIO_ACCESS_KEY
          value: finogeeks
        - name: MINIO_SECRET_KEY
          value: '!encAnK88#@abIObcd)5'
        image: {{ .Values.images.minio }}
        name: minio
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: minio-claim0
      restartPolicy: Always
      
        
      volumes:
      - name: minio-claim0
        persistentVolumeClaim:
          claimName: minio-claim0
status: {}
