apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    app: mongo-claim0
  name: mongo-claim0
spec:
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 20G
status: {}
