apiVersion: v1
kind: Service
metadata:
  labels:
    app: mop-article-pub-center
  name: mop-article-pub-center
spec:
  ports:
    - name: "port"
      port: 34000
      targetPort: 34000
    - name: "monitor"
      port: 9092
      targetPort: 9092
  selector:
    app: mop-article-pub-center
