apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: mop-netdisk-proxy
  name: mop-netdisk-proxy
spec:
  ports:
    - name: "port"
      port: 41000
      targetPort: 41000
    - name: "monitor"
      port: 9092
      targetPort: 9092
  selector:
    io.kompose.service: mop-netdisk-proxy