apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: mop-private-init-server
  name: mop-private-init-server
spec:
  ports:
  - name: "port"
    port: 8080
    targetPort: 8080
  - name: "monitor"
    port: 9092
    targetPort: 9092
  selector:
    io.kompose.service: mop-private-init-server