apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    app: applets-ecol-account
  name: applets-ecol-account
spec:
  selector:
    matchLabels:
      app: applets-ecol-account
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: applets-ecol-account
    spec:
      containers:
      - env:
        - name: COMMON_VERIFY_CODE
          value: finogeeks
        - name: DB_NAME
          value: mop-private-applets-ecol-account
        - name: DEVELOP_LEVEL
          value: debug
        - name: DEVICE_SECURITY_URL_PREFIX
          value: http://applets-ecol-device-security:8080
        - name: ENV
          value: mop-private
        - name: KAFKA_ADDR
          value: kafka:9092
        - name: KONG_URL_PREFIX
          value: http://gateway:8001
        - name: MONGO_URL
          value: mongo
        image: {{ .Values.images.applets_ecol_account }}
        name: applets-ecol-account
        resources: {}
      restartPolicy: Always
      
