apiVersion: v1
kind: Service
metadata:
  labels:
    app: mop-open-api
  name: mop-open-api
spec:
  ports:
    - name: "port"
      port: 42000
      targetPort: 42000
    - name: "monitor"
      port: 9092
      targetPort: 9092
  selector:
    app: mop-open-api
