apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    app: mop-app-gray-statistics-center
  name: mop-app-gray-statistics-center
spec:
  selector:
    matchLabels:
      app: mop-app-gray-statistics-center
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mop-app-gray-statistics-center
    spec:
      containers:
      - args:
        - sh
        - -c
        - |-
          sleep 30s
          /opt/mop-app-gray-statistics-center
        env:
        - name: HTTP_PORT
          value: "8080"
        - name: KAFKA_ADDR
          value: kafka:9092
        - name: MONGO_URL
          value: mongo
        image: {{ .Values.images.mop_app_gray_statistics_center }}
        name: mop-app-gray-statistics-center
        resources: {}
      restartPolicy: Always
      
        
status: {}
