apiVersion: v1
kind: Service
metadata:
  labels:
    app: mop-front-document
  name: mop-front-document
spec:
  ports:
  - name: "port"
    port: 80
    targetPort: 80
  - name: "monitor"
    port: 9092
    targetPort: 9092
  selector:
    app: mop-front-document
