apiVersion: v1
kind: Service
metadata:
  labels:
    app: mop-control-manager
  name: mop-control-manager
spec:
  ports:
  - name: "port"
    port: 8080
    targetPort: 8080
  - name: "monitor"
    port: 9092
    targetPort: 9092
  selector:
    app: mop-control-manager
