apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: mop-app-manage-svr
  name: mop-app-manage-svr
spec:
  ports:
  - name: "mop-app-manage-svr"
    port: 9092
    targetPort: 9092
  selector:
    io.kompose.service: mop-app-manage-svr
status:
  loadBalancer: {}
