apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    app: scattered-page
  name: scattered-page
spec:
  selector:
    matchLabels:
      app: scattered-page
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: scattered-page
    spec:
      containers:
      - env:
        - name: API_URL
          value: "https://finchat-mop-private.finogeeks.club"
        - name: NGINX_PORT
          value: "80"
        image: {{ .Values.images.scattered_page }}
        name: scattered-page
        resources: {}
      restartPolicy: Always
      
        
status: {}
