apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    app: zookeeper
  name: zookeeper
spec:
  ports:
  - name: "zookeeper"
    port: 2181
    targetPort: 2181
  selector:
    app: zookeeper
status:
  loadBalancer: {}
