apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    app: gateway
  name: gateway
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gateway
    spec:
      initContainers:
        - name: kong-migrations
          image: {{ .Values.images.kong_migrations }}
          command: ["/bin/sh","-c"]
          args: ["kong migrations bootstrap"]
          env:
          - name: KONG_DATABASE
            value: postgres
          - name: KONG_PG_DATABASE
            value: kong
          - name: KONG_PG_HOST
            value: kong-db
          - name: KONG_PG_PASSWORD
            value: kong@@123321
          - name: KONG_PG_PORT
            value: "5432"
          - name: KONG_PG_USER
            value: kong
          imagePullPolicy: Always
        - name: kong-migrations-finish
          image: {{ .Values.images.kong_migrations_up }}
          command: ["/bin/sh","-c"]
          args: ["kong migrations finish"]
          env:
          - name: KONG_DATABASE
            value: postgres
          - name: KONG_PG_DATABASE
            value: kong
          - name: KONG_PG_HOST
            value: kong-db
          - name: KONG_PG_PASSWORD
            value: kong@@123321
          - name: KONG_PG_PORT
            value: "5432"
          - name: KONG_PG_USER
            value: kong
      containers:
      - env:
        - name: KONG_ADMIN_ACCESS_LOG
          value: /dev/stdout
        - name: KONG_ADMIN_ERROR_LOG
          value: /dev/stderr
        - name: KONG_ADMIN_LISTEN
          value: 0.0.0.0:8001, 0.0.0.0:8444
        - name: KONG_PG_DATABASE
          value: kong
        - name: KONG_PG_HOST
          value: kong-db
        - name: KONG_PG_PASSWORD
          value: kong@@123321
        - name: KONG_PG_PORT
          value: "5432"
        - name: KONG_PG_USER
          value: kong
        - name: KONG_PLUGINS
          value: oidc,jwt,mop
        - name: KONG_PROXY_ACCESS_LOG
          value: /dev/stdout
        - name: KONG_PROXY_ERROR_LOG
          value: /dev/stderr
        - name: KONG_PROXY_LISTEN
          value: 0.0.0.0:8000, 0.0.0.0:8443
        - name: TZ
          value: Asia/Shanghai
        image: {{ .Values.images.gateway }}
        livenessProbe:
          exec:
            command:
            - kong
            - health
          failureThreshold: 10
          periodSeconds: 10
          timeoutSeconds: 10
        name: gateway
        ports:
        - containerPort: 8000
        resources: {}
      restartPolicy: Always
      imagePullSecrets:
        - name: {{ .Values.k8s_imagePullSecrets }}
status: {}
