apiVersion: v1
kind: Service
metadata:
  labels:
    app: mop-rule-engine-svr
  name: mop-rule-engine-svr
spec:
  ports:
    - name: "port"
      port: 8080
      targetPort: 8080
    - name: "monitor"
      port: 9092
      targetPort: 9092
  selector:
    app: mop-rule-engine-svr
