apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    app: mop-init
  name: mop-init
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mop-init
    spec:
      containers:
      - args:
        - sh
        - -c
        - |
          sleep 700s
          node download.js
          node index.js
        env:
        - name: ENV_TYPE
          value: mop
        image: {{ .Values.images.mop_init }}
        name: mop-init
        resources: {}
      restartPolicy: OnFailure
      imagePullSecrets:
        - name: {{ .Values.k8s_imagePullSecrets }}
status: {}
