apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    app: mop-front-mechanism
  name: mop-front-mechanism
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mop-front-mechanism
    spec:
      containers:
      - env:
        - name: API_URL
          value: http://gateway:8000/
        - name: NGINX_PORT
          value: "80"
        image: {{ .Values.images.mop_front_mechanism }}
        name: mop-front-mechanism
        resources: {}
      restartPolicy: Always
      imagePullSecrets:
        - name: {{ .Values.k8s_imagePullSecrets }}
status: {}
