apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: mop-feedback-svr
  name: mop-feedback-svr
spec:
  ports:
    - name: "port"
      port: 39000
      targetPort: 39000
    - name: "monitor"
      port: 9092
      targetPort: 9092
  selector:
    io.kompose.service: mop-feedback-svr