apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: mop-basic-pack-svr
  name: mop-basic-pack-svr
spec:
  ports:
    - name: "port"
      port: 38000
      targetPort: 38000
    - name: "monitor"
      port: 9092
      targetPort: 9092
  selector:
    io.kompose.service: mop-basic-pack-svr