apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: applets-ecol-domain
  name: applets-ecol-domain
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: applets-ecol-domain
    spec:
      containers:
      - env:
        - name: KAFKA_ADDR
          value: kafka:9092
        - name: MONGO_URL
          value: mongo
        - name: WHITELIST_DOMAIN_MAX_NUM
          value: "1000"
        image: {{ .Values.images.applets_ecol_domain }}
        name: applets-ecol-domain
        resources: {}
      restartPolicy: Always
      imagePullSecrets:
        - name: {{ .Values.k8s_imagePullSecrets }}
status: {}
