apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: netdisk
  name: netdisk
spec:
  ports:
  - name: "netdisk"
    port: 9999
    targetPort: 9999
  selector:
    io.kompose.service: netdisk
status:
  loadBalancer: {}
