apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: scattered-page
  name: scattered-page
spec:
  ports:
  - name: "port"
    port: 80
    targetPort: 80
  - name: "monitor"
    port: 9092
    targetPort: 9092
  selector:
    io.kompose.service: scattered-page
