apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: applets-ecol-device-security
  name: applets-ecol-device-security
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: applets-ecol-device-security
    spec:
      containers:
      - env:
        - name: ACTIVE_MIN
          value: "60"
        - name: DB_NAME
          value: mop-private-applets-ecol-device-security
        - name: KONG_URL_PREFIX
          value: http://gateway:8001
        - name: MAX_COROUTINES_NUM
          value: "100"
        - name: MONGO_URL
          value: mongo
        image: applets-ecol-device-security
        name: applets-ecol-device-security
        resources: {}
      restartPolicy: Always
status: {}
