apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: gateway-init
  name: gateway-init
spec:
  containers:
  - env:
    - name: API_GATEWAY_ENV
      value: mop-compose
    - name: KONG_ADMIN_URL
      value: http://gateway:8001
    - name: LOG_LEVEL
      value: info
    image: gateway-init
    name: gateway-init
    resources: {}
  restartPolicy: OnFailure
status: {}
