apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: kong-migrations
  name: kong-migrations
spec:
  containers:
  - args:
    - kong
    - migrations
    - bootstrap
    env:
    - name: KONG_DATABASE
      value: postgres
    - name: KONG_PG_DATABASE
      value: kong
    - name: KONG_PG_HOST
      value: kong-db
    - name: KONG_PG_PASSWORD
      value: kong@@123321
    - name: KONG_PG_PORT
      value: "5432"
    - name: KONG_PG_USER
      value: kong
    image: kong-migrations
    name: kong-migrations
    resources: {}
  restartPolicy: OnFailure
status: {}
