apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: minio
  name: minio
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: minio
    spec:
      containers:
      - args:
        - server
        - /data
        env:
        - name: MINIO_ACCESS_KEY
          value: finogeeks
        - name: MINIO_SECRET_KEY
          value: '!encAnK88#@abIObcd)5'
        image: {{ .Values.images.minio }}
        name: minio
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: minio-claim0
      restartPolicy: Always
      imagePullSecrets:
        - name: {{ .Values.k8s_imagePullSecrets }}
      volumes:
      - name: minio-claim0
        persistentVolumeClaim:
          claimName: minio-claim0
status: {}
