apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: mop-basic-pack-svr
  name: mop-basic-pack-svr
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mop-basic-pack-svr
    spec:
      containers:
      - env:
        - name: BASIC_LATEST_VER_KEY
          value: mop_latest_basic_pack_key_private
        - name: BASIC_SEQ_KEY
          value: mop_basic_pack_sequence_key_private
        - name: DB_NAME
          value: mop-basic-pack-private
        - name: HTTP_PORT
          value: "38000"
        - name: KAFKA_ADDR
          value: kafka:9092
        - name: MONGO_URL
          value: mongo
        - name: NOTIFY_TOPIC
          value: mop_private_notify_data_topic
        - name: PUBLISH_ENV
          value: compose
        - name: REDIS_URL
          value: redis://redis:6379/10
        image: mop-basic-pack-svr
        name: mop-basic-pack-svr
        resources: {}
      restartPolicy: Always
status: {}
