apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: mop-open-api
  name: mop-open-api
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mop-open-api
    spec:
      containers:
      - env:
        - name: APM_REPORT_HOST
          value: http://data-report:3000
        - name: HTTP_PORT
          value: "42000"
        - name: MONGO_URL
          value: mongo
        - name: REDIS_URL
          value: redis://redis:6379/10
        image: {{ .Values.images.mop-open-api }}
        name: mop-open-api
        resources: {}
      restartPolicy: Always
      imagePullSecrets:
        - name: {{ .Values.k8s_imagePullSecrets }}
status: {}
