apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: mop-feedback-svr
  name: mop-feedback-svr
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mop-feedback-svr
    spec:
      containers:
      - env:
        - name: DB_NAME
          value: mop-private-feedback-svr
        - name: GET_ORGAN_INFO_URL
          value: http://applets-ecol-account:8080/api/v1/mop/applets-ecol-account/organ/business/info/
        - name: HTTP_PORT
          value: "39000"
        - name: MONGO_URL
          value: mongo
        - name: PUBLISH_ENV
          value: compose
        - name: ZIPKIN_URL
        image: mop-feedback-svr
        name: mop-feedback-svr
        resources: {}
      restartPolicy: Always
status: {}
