apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: mop-rule-cron-job
  name: mop-rule-cron-job
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mop-rule-cron-job
    spec:
      containers:
      - image: mop-rule-cron-job
        name: mop-rule-cron-job
        resources: {}
      restartPolicy: Always
status: {}
