apiVersion: apps/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: mop-control-manager
  name: mop-control-manager
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mop-control-manager
    spec:
      containers:
      - env:
        - name: COMMON_APM_URL
          value: https://mop-apm.finogeeks.com
        - name: DB_NAME
          value: mop-control-manager
        - name: MONGO_URL
          value: mongo
        image: {{ .Values.images.mop_control_manager }}
        name: mop-control-manager
        resources: {}
      restartPolicy: Always
      imagePullSecrets:
        - name: {{ .Values.k8s_imagePullSecrets }}
status: {}
