apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: mop-netdisk-proxy
  name: mop-netdisk-proxy
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mop-netdisk-proxy
    spec:
      containers:
      - env:
        - name: HTTP_PORT
          value: "41000"
        - name: MONGO_URL
          value: mongo
        - name: PUBLISH_ENV
          value: private
        - name: REDIS_ADDR
          value: redis://redis:6379/10
        image: {{ .Values.images.mop-netdisk-proxy }}
        name: mop-netdisk-proxy
        resources: {}
      restartPolicy: Always
      imagePullSecrets:
        - name: {{ .Values.k8s_imagePullSecrets }}
status: {}
