apiVersion: apps/v1beta2
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: data-report
  name: data-report
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: data-report
    spec:
      containers:
      - env:
        - name: ACCOUNT_PROVIDER_URL
          value: http://applets-ecol-account:8080/api/v1/mop/applets-ecol-account/organ/platform/account/organInfo/
        - name: KAFKA_ADDESS
          value: kafka:9092
        - name: MONGO_URL
          value: mongo
        image: {{ .Values.images.data_report }}
        name: data-report
        resources: {}
      restartPolicy: Always
      imagePullSecrets:
        - name: {{ .Values.k8s_imagePullSecrets }}
status: {}
