apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: applets-ecol-notify
  name: applets-ecol-notify
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: applets-ecol-notify
    spec:
      containers:
      - env:
        - name: ACCOUNT_HOST
          value: http://applets-ecol-account:8080
        - name: KAFKA_ADDR
          value: kafka:9092
        - name: MONGO_URL
          value: mongo
        image: {{ .Values.images.applets_ecol_notify }}
        name: applets-ecol-notify
        resources: {}
      restartPolicy: Always
      imagePullSecrets:
        - name: {{ .Values.k8s_imagePullSecrets }}
status: {}
