apiVersion: apps/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: mop-license-checker
  name: mop-license-checker
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mop-license-checker
    spec:
      containers:
      - args:
        - sh
        - -c
        - |
          sleep 30s
          /opt/mop-license-checker
        env:
        - name: LICENSE
          value: gyxXK0fvBxoS5Tdx6srr/nX8vTC6wyKyDI4WjsbRQLM7zrWxfnD8zLSXra8jANqdBAIt+EMk4zfpjUhIOXV/SbsSnfYn/rL50egb2E4KwGX7I262Hkkc72HkpegoNfLY0NqlpOIIc5vQOCJdMJ13H+uPaS5hNP7SYOoYMp7kXr2d7S70QlB9l9T4f1exeLNXJsEPayp5oZW+kKeY72EumnjTSFOCyQqx1HZTMh1W7VKSDua+D+Ukfa7R/JpTmad52TanE/ObSgfqQu1qctQVmleoVDD6M/2qq4qbtVecL+AYBy9Cr9XcLCo87swRRN3WW/RVpKDKLicQODsiLE3tw99LCSTR4dW7oPJwknSUU5nR9yLCUMvTAvV38G1ax8TMCevIK2rXNQn3gwtb2k8Re209DquqrSs2IRnag5+z986oAN+qxuIyxoXD6SurdIq43i7dBbvXPAFiUEauX6Hcfrk/YNvEfxBQBWUzUSuORkfDo31FhK5nVIS9TCPNcNh+H6E31EBKS0qwT9HZ31WrpFixkWZERczRTOBXgAjhZkfUgDRHVMpg+Zb4WVDuC2QZeTUILziFM3+DzxkUBKljuEEWHx6qRly7PAk03GK2hKCUiczPT02aX/VIrSeBsacXoGdVAt7xw/eeM0aaKMs8R9+Jf1pEyWcKz2xiQJq0riFlmEtSf3KF6SHcNTKZlJ17cRUVeNto3acoN6rb5mhv7Ioi4Q0hL029o+MP3ynzruOwMRZiaBvpIyB/94vK8L2j3txZwrJuf6ZRLCg75UGOlkGvCpQbte2djj27u+/xlVRj+IBXlPoCbTnthYHLHLpovZZX5s7/FJskbAYhrRP1dL/TOebRWwAUNrfxBTkB/LyqBA7g25FlAVEseq5noMHrmxNjI/FuL0ggzW+czbpS2Lho2AmxBVbEljrgbjG9ALj4zOHdpl96Jo2tKlbRPpQoi92YzbSw0nJaJjd9vwDnC0UQeeRXme5pZp970PDnJ3nTEXBpuqZbb7Rh62WVK8UQD5==
        image: {{ .Values.images.mop_license_checker }}
        name: mop-license-checker
        resources: {}
      restartPolicy: Always
      imagePullSecrets:
        - name: {{ .Values.k8s_imagePullSecrets }}
status: {}
